---
title: "Untitled"
output: html_document
date: "2022-09-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, phdWork, ggrepel)
```


```{r}
set.seed(1234)
n <- 80
r <- 8
L <- 2

mu1 <- rep(r/sqrt(L), L)
mu2 <- rep(-r/sqrt(L), L)
I <- diag(1, L)

df <- rbind(MASS::mvrnorm(n = n/2, mu = mu1, Sigma = I), MASS::mvrnorm(n = n/2, mu = mu2, Sigma = I))
colnames(df) <- c("x", "y")
df <- as_tibble(df)
```

```{r}
centriods <- rbind(mu1, mu2, rep(0, L))
colnames(centriods) <- c("x", "y")
centriods <- as_tibble(centriods)
centriods <- centriods %>% 
  mutate(label = c("r", 
                   "-r", 
                   "0"),
         col = as.factor(1:3))
height <- 5
```


```{r}
colMeans(df[1:40,])
colMeans(df[41:80,])
colMeans(df)
```


```{r}
df %>% 
  ggplot(aes(x, y)) +
  geom_point() +
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  geom_abline(slope = 1, intercept = 0, colour = "gray90", lty = 2) +
  geom_point(data = centriods, col = "darkorange", size = 4) +
  geom_label_repel(data = centriods, 
                   aes(label = label),   col = "darkorange",
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50',
                   size = 5) +
  harrypotter::scale_colour_hp_d("ravenclaw") +
  labs(x = NULL, y = NULL) +
  theme_minimal() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        strip.text = element_text(size = 20),
        strip.background = element_rect(fill = "gray70"),
        plot.title = element_text(hjust = 0.5))
ggsave("../../002_Thesis/01_initial_draft/img/tangent_score_sim.png",
       height = height, width = 1.618 * height)
```



