---
title: "03_cobre_tables"
output: 
  pdf_document:
    keep_tex: TRUE
date: "2022-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(tidyverse, kableExtra)
```

```{r}
cv_res <- read_rds("../results/abide_cv_results.Rds")
```

```{r}
mean_round <- 2
se_round <- 3
```


```{r}
tab <- cv_res %>% 
  filter(K <= 10) %>% 
  select(K, r2 = r2_1, rmse:spec) %>% 
  group_by(K) %>% 
  summarise(mean_r2 = mean(r2),
            mean_rmse = mean(rmse),
            sd_r2 = sd(r2),
            sd_rmse = sd(rmse),
            mean_acc = mean(accuracy),
            mean_sens = mean(sens),
            mean_spec = mean(spec),
            sd_acc = sd(accuracy),
            sd_sens = sd(sens),
            sd_spec = sd(spec)
  ) %>% 
  mutate(across(contains("sd"), ~.x/sqrt(10)))
```

```{r}
find_within_1_se <- function(tab){
  k_min <- tab %>% 
    slice_min(mean_rmse) %>% 
    pull(K)
  within_one <- tab$mean_rmse[k_min] + c(-1, 1) * tab$sd_rmse[k_min]
  tab %>% 
    select(K, mean_rmse, sd_rmse) %>% 
    mutate(within = ifelse(mean_rmse >= within_one[1] & mean_rmse <= within_one[2], T, F)) %>% 
    filter(within) %>% 
    slice_min(K) %>% 
    pull(K)
}
optimal_k <- find_within_1_se(tab)
```



```{r abide_cv_results} 
tab %>% 
  mutate(
    r2 = str_c(round(mean_r2, mean_round), " (", round(sd_r2, se_round), ")"),
    rmse = str_c(round(mean_rmse, mean_round), " (", round(sd_rmse, se_round), ")"),
    accuracy = str_c(round(mean_acc, mean_round), " (", round(sd_acc, se_round), ")"),
    sens = str_c(round(mean_sens, mean_round), " (", round(sd_sens, se_round), ")"),
    spec = str_c(round(mean_spec, mean_round), " (", round(sd_spec, se_round), ")"),
  ) %>% 
  select(K, r2:spec) %>% 
  kbl(booktabs = T,
      col.names = c("K", "$R^2$", "RMSE", "Accuracy", "Sensitivity", "Specificity"),
      caption = "Mean (sd) 10-fold cross validation results for Riemannian PLS on the ABIDE dataset for the first ten latent variables extracted.  The full model metrics are the multivariate $R^2$ and RMSE on recovering age, subject group, sex, and eye status.  The group classification metrics look at the classifcation accuracy of the Riemannian PLS model for subject group only.  All metrics are optimised at $K = 3$ (blue).", 
      position = "htbp", 
      align = c("l", "c", "c", "c", "c", "c"), 
  ) %>% 
  kable_styling(latex_options = "striped") %>% 
  row_spec(optimal_k, background = "blue!20") %>% 
  column_spec(3, border_right = T) %>% 
  add_header_above(c(" " = 1, "Full model metrics" = 2, "Group classification" = 3))
```





```{r}
cv_res_euc <- read_rds("../results/abide_cv_results_euclidean.Rds")
cv_res_fish <- read_rds("../results/abide_cv_results_fisher.Rds")
```

```{r}
return_best_mod <- function(cv, method){
  tab <- cv %>% 
    filter(K <= 10) %>% 
    select(K, r2 = r2_1, rmse:spec) %>% 
    group_by(K) %>% 
    summarise(mean_r2 = mean(r2),
              mean_rmse = mean(rmse),
              sd_r2 = sd(r2),
              sd_rmse = sd(rmse),
              mean_acc = mean(accuracy),
              mean_sens = mean(sens),
              mean_spec = mean(spec),
              sd_acc = sd(accuracy),
              sd_sens = sd(sens),
              sd_spec = sd(spec)) %>% 
    mutate(
      across(contains("sd"), ~.x/sqrt(10))
    )
  
  optimal_k <- find_within_1_se(tab)
  
  res <- tab %>% 
    mutate(
      r2 = str_c(round(mean_r2, mean_round), " (", round(sd_r2, se_round), ")"),
      rmse = str_c(round(mean_rmse, mean_round), " (", round(sd_rmse, se_round), ")"),
      accuracy = str_c(round(mean_acc, mean_round), " (", round(sd_acc, se_round), ")"),
      sens = str_c(round(mean_sens, mean_round), " (", round(sd_sens, se_round), ")"),
      spec = str_c(round(mean_spec, mean_round), " (", round(sd_spec, se_round), ")"),
    ) %>% 
    select(K, r2:spec) %>%
    ungroup() %>% 
    filter(K == optimal_k) %>% 
    mutate(method = method) %>% 
    select(method, everything())
  return(res)
}
```

```{r}
df <- bind_rows(return_best_mod(cv_res, "Riemannian"), 
                return_best_mod(cv_res_euc, "Raw correlations"),
                return_best_mod(cv_res_fish, "Fisher correlations")) %>% 
  pivot_longer(r2:spec, names_to = "metric") %>% 
  mutate(name = str_c(method, " (K =", K, ")")) %>% 
  select(-method, -K) %>% 
  pivot_wider(names_from = name, values_from = value) %>% 
  mutate(metric = case_when(
    metric == "rmse" ~ "RMSE",
    metric == "r2" ~ "$R^2$",
    metric == "accuracy" ~ "Accuracy", 
    metric == "sens" ~ "Sensitivity", 
    TRUE ~ "Specificity"
  ))
```

```{r abide_cv_compare}
df %>% 
  kbl(booktabs = T,
      caption = "Mean (SE) 10-fold cross validation results for Riemannian PLS on the ABIDE dataset, as well as Euclidean PLS using the raw correlations and the Fisher transformed correlations.  The value $K$ represents the optimal number of latent variables for each setting.  The full model metrics are the multivariate $R^2$ and RMSE on recovering age, subject group, eye status, and sex.  The group classification metrics look at the classifcation accuracy of the PLS model for subject group only.  Riemannian PLS is the best model over all model metrics.", 
      position = "htbp", 
      col.names = c("", colnames(df)[2:4])
      # align = c("l", "r", "r", "r", "r", "r"), 
  ) %>% 
  kable_styling(latex_options = "striped") %>% 
  pack_rows(group_label = "Full model metrics (SE)", start_row = 1, end_row = 2) %>% 
  pack_rows(group_label = "Group classification (SE)", start_row = 3, end_row = 5) %>% 
  column_spec(1, italic = TRUE, border_right = T) %>% 
  column_spec(2, bold = TRUE) 
```








